# domains.py
# Comprehensive list of corporate email domains for global financial institutions
# Categories: IB, Buy-side, Asset Management, Quant, PE, Real Assets, and Institutional Investors.

COMPANY_DOMAINS = {

    # =========================
    # Bulge Bracket / Global IB
    # =========================
    "Goldman Sachs": "gs.com",
    "JPMorgan": "jpmorgan.com",
    "Morgan Stanley": "morganstanley.com",
    "Bank of America": "bofa.com",
    "Citigroup": "citi.com",
    "Barclays": "barclays.com",
    "UBS": "ubs.com",
    "Deutsche Bank": "db.com",
    "BNP Paribas": "bnpparibas.com",
    "HSBC": "hsbc.com",
    "Credit Suisse": "credit-suisse.com",
    "RBC": "rbc.com",
    "Société Générale": "socgen.com",
    "Nomura": "nomura.com",
    "Mizuho": "mizuho.com",
    "SMBC": "smbcgroup.com",
    "MUFG": "mufg.jp",
    "Wells Fargo": "wellsfargo.com",
    "TD Securities": "tdsecurities.com",
    "BMO Capital Markets": "bmo.com",
    "Standard Chartered": "sc.com",
    "ING": "ing.com",
    "ANZ": "anz.com",
    "Macquarie": "macquarie.com",
    "NatWest": "natwest.com",
    "Danske Bank": "danskebank.com",
    "Nordea": "nordea.com",

    # =========================
    # Boutique & MM IB
    # =========================
    "Jefferies": "jefferies.com",
    "Lazard": "lazard.com",
    "Evercore": "evercore.com",
    "Centerview Partners": "centerviewpartners.com",
    "PJT Partners": "pjtpartners.com",
    "Moelis": "moelis.com",
    "Houlihan Lokey": "hl.com",
    "Perella Weinberg": "pwpartners.com",
    "Rothschild & Co": "rothschildandco.com",
    "Greenhill": "greenhill.com",
    "Guggenheim Securities": "guggenheimpartners.com",
    "Cantor Fitzgerald": "cantor.com",
    "Cowen": "cowen.com",
    "Oppenheimer": "opco.com",
    "Stifel": "stifel.com",
    "Piper Sandler": "pipersandler.com",
    "Raymond James": "raymondjames.com",
    "William Blair": "williamblair.com",
    "Lincoln International": "lincolninternational.com",
    "M. Klein & Company": "mkleinandcompany.com",
    "Robey Warshaw": "robeywarshaw.com",
    "LionTree": "liontree.com",
    "Dyal Capital": "dyalco.com",
    "Foros Group": "forosgroup.com",
    "Zaoui & Co": "zaouiandco.com",
    "Ardea Partners": "ardeapartners.com",
    "Allen & Company": "allenco.com",
    "Baird": "rwbaird.com",
    "Harris Williams": "harriswilliams.com",
    "Stephens": "stephens.com",
    "Janney Montgomery Scott": "janney.com",
    "Canaccord Genuity": "canaccordgenuity.com",
    "KeyBanc": "key.com",
    "Truist Securities": "truist.com",
    "Regions Securities": "regions.com",
    "PNC": "pnc.com",

    # =========================
    # Asset Management
    # =========================
    "BlackRock": "blackrock.com",
    "Vanguard": "vanguard.com",
    "Fidelity": "fidelity.com",
    "Capital Group": "capitalgroup.com",
    "Wellington Management": "wellington.com",
    "PIMCO": "pimco.com",
    "T. Rowe Price": "troweprice.com",
    "Invesco": "invesco.com",
    "Franklin Templeton": "franklintempleton.com",
    "PGIM": "pgim.com",
    "Nuveen": "nuveen.com",
    "State Street": "ssga.com",
    "Dimensional Fund Advisors": "dfaus.com",
    "AQR": "aqr.com",
    "AllianceBernstein": "alliancebernstein.com",
    "Janus Henderson": "janushenderson.com",
    "Neuberger Berman": "nb.com",
    "Loomis Sayles": "loomissayles.com",
    "Western Asset": "westernasset.com",
    "Federated Hermes": "federatedhermes.com",
    "Schroders": "schroders.com",
    "Amundi": "amundi.com",
    "BNY Mellon": "bnymellon.com",
    "Columbia Threadneedle": "columbiathreadneedle.com",
    "Lord Abbett": "lordabbett.com",
    "MFS": "mfs.com",
    "Putnam": "putnam.com",
    "Legal & General": "lgim.com",
    "Aviva Investors": "avivainvestors.com",
    "Man Group": "man.com",
    "Geode Capital": "geodecapital.com",
    "Northern Trust": "northerntrust.com",
    "Payden & Rygel": "payden.com",
    "DoubleLine": "doubleline.com",
    "Harris Associates": "harrisassoc.com",
    "Causeway Capital": "causewaycap.com",
    "TCW": "tcw.com",
    "Wasatch": "wasatchglobal.com",
    "Brown Advisory": "brownadvisory.com",
    "Diamond Hill": "diamond-hill.com",
    "Polen Capital": "polencapital.com",
    "Sands Capital": "sandscapital.com",
    "Mondrian": "mondrian.com",
    "Ariel Investments": "arielinvestments.com",
    "Brandes": "brandes.com",
    "Fiduciary Trust": "fiduciarytrust.com",
    "First Eagle": "firsteagle.com",
    "Pictet": "pictet.com",
    "Lombard Odier": "lombardodier.com",
    "Carmignac": "carmignac.com",
    "Eurazeo": "eurazeo.com",
    "Ninety One": "ninetyone.com",
    "Abrdn": "abrdn.com",
    "Jupiter": "jupiteram.com",
    "Robeco": "robeco.com",
    "Candriam": "candriam.com",
    "DWS": "dws.com",
    "Generali Investments": "generali-investments.com",
    "Aegon Asset Management": "aegonam.com",
    "Nikko Asset Management": "nikkoam.com",
    "Mirae Asset": "miraeasset.com",
    "China AMC": "chinaamc.com",
    "E Fund": "efunds.com.cn",
    "Victory Capital": "victorycapital.com",
    "Dodge & Cox": "dodgeandcox.com",
    "Barings": "barings.com",
    "American Century": "americancentury.com",
    "Calamos Investments": "calamos.com",
    "Artisan Partners": "artisanpartners.com",
    "WCM Investment Management": "wcminvest.com",
    "Matthews Asia": "matthewsasia.com",
    "Baillie Gifford": "bailliegifford.com",
    "Pzena Investment Management": "pzena.com",
    "Brown Capital Management": "browncapital.com",
    "GMO": "gmo.com",
    "Jennison Associates": "jennison.com",
    "ClearBridge Investments": "clearbridge.com",
    "Causeway Capital": "causewaycap.com",
    "Harding Loevner": "hardingloevner.com",
    "Lord Abbett": "lordabbett.com",
    "Columbia Management": "columbiathreadneedle.com",
    "Capital Research": "capitalgroup.com",
    "T. Rowe Price Associates": "troweprice.com",
    "Putnam Management": "putnam.com",
    "VanEck": "vaneck.com",
    "SEI Investments": "seic.com",

    # Insurance & Insurance Asset Management
    "Prudential Investment Management": "pgim.com",
    "MetLife Investment Management": "metlifeinvestments.com",
    "AXA Investment Managers": "axa-im.com",
    "Allianz Global Investors": "allianzgi.com",
    "Swiss Re Asset Management": "swissre.com",
    "Munich Re Asset Management": "munichre.com",
    "Legal & General Capital": "lgim.com",
    "Manulife Investment Management": "manulifeim.com",
    "Sun Life Asset Management": "sunlife.com",
    "Voya Investment Management": "voya.com",
    "Generali Asset Management": "generali-investments.com",
    "Aegon Asset Management": "aegonam.com",
    "Prudential Financial Asset Management": "prudential.com",
    "Aviva Investors": "avivainvestors.com",
    "Guardian Life": "guardianlife.com",
    "New York Life Investments": "nylim.com",
    "MassMutual Asset Management": "massmutual.com",
    "Principal Global Investors": "principalglobal.com",
    
    # =========================
    # Hedge Funds / Alternatives
    # =========================
    "Bridgewater": "bridgewater.com",
    "Citadel": "citadel.com",
    "Citadel Securities": "citadelsecurities.com",
    "Millennium": "mlp.com",
    "Two Sigma": "twosigma.com",
    "D. E. Shaw": "deshaw.com",
    "Point72": "point72.com",
    "Balyasny": "bamfunds.com",
    "Ares": "aresmgmt.com",
    "Apollo": "apollo.com",
    "Blackstone": "blackstone.com",
    "KKR": "kkr.com",
    "Carlyle": "carlyle.com",
    "TPG": "tpg.com",
    "Oaktree": "oaktreecapital.com",
    "Bain Capital": "baincapital.com",
    "Warburg Pincus": "warburgpincus.com",
    "General Atlantic": "generalatlantic.com",
    "Silver Lake": "silverlake.com",
    "Vista Equity": "vistaequitypartners.com",
    "Advent": "adventinternational.com",
    "Permira": "permira.com",
    "Brookfield": "brookfield.com",
    "Blue Owl": "blueowl.com",
    "Elliott": "elliottmgmt.com",
    "Third Point": "thirdpoint.com",
    "Pershing Square": "pershingsquareholdings.com",
    "Farallon": "faralloncapital.com",
    "Lone Pine": "lonepinecapital.com",
    "Viking Global": "vikingglobal.com",
    "Coatue": "coatue.com",
    "Tiger Global": "tigerglobal.com",
    "Schonfeld": "schonfeld.com",
    "ExodusPoint": "exoduspoint.com",
    "Graham Capital": "grahamcapital.com",
    "Caxton": "caxton.com",
    "Tudor": "tudor.com",
    "Paloma": "palomapartners.com",
    "Bracebridge": "bracebridgecapital.com",
    "CQS": "cqs.com",
    "Silver Point": "silverpointcapital.com",
    "Mariner": "marinerinvestmentgroup.com",
    "Davidson Kempner": "dkpartners.com",
    "Rokos": "rokoscapital.com",
    "Stone Ridge": "stoneridge.com",
    "BlueCrest": "bluecrestcapital.com",
    "HPS": "hpspartners.com",
    "King Street": "kingstreet.com",
    "Canyon Partners": "canyonpartners.com",
    "Värde": "varde.com",
    "Angelo Gordon": "angelogordon.com",
    "Centerbridge": "centerbridge.com",
    "Baupost": "baupost.com",
    "Sculptor": "sculptor.com",
    "Avenue Capital": "avenuecapital.com",
    "GoldenTree": "goldentree.com",

    # =========================
    # Quant / Prop Trading
    # =========================
    "Jane Street": "janestreet.com",
    "IMC Trading": "imc.com",
    "Optiver": "optiver.com",
    "Flow Traders": "flowtraders.com",
    "DRW": "drw.com",
    "Jump Trading": "jumptrading.com",
    "Hudson River Trading": "hudsonrivertrading.com",
    "Tower Research": "tower-research.com",
    "SIG": "sig.com",
    "Virtu": "virtu.com",
    "Old Mission": "oldmissioncapital.com",
    "Akuna Capital": "akunacapital.com",
    "Belvedere Trading": "belvederetrading.com",
    "Geneva Trading": "genevatrading.com",
    "PEAK6": "peak6.com",
    "Spot Trading": "spottradingllc.com",
    "Group One Trading": "group1.com",
    "CTC Trading": "chicagotrading.com",
    "Wolverine Trading": "wolve.com",
    "TransMarket Group": "tmg-llc.com",
    "Headlands": "headlandstech.com",
    "Quantlab": "quantlab.com",
    "Teza": "teza.com",
    "WorldQuant": "worldquant.com",
    "Five Rings": "fiverings.com",
    "Radix Trading": "radixtrading.com",
    "Volant Trading": "volanttrading.com",
    "Hard Eight Trading": "hardeight.com",
    "Squarepoint Capital": "squarepoint-capital.com",
    "XTX Markets": "xtxmarkets.com",
    "G-Research": "g-research.co.uk",
    "IMC Financial Markets": "imc.com",
    "Susquehanna International Group": "sig.com",
    "Jane Street Capital": "janestreet.com",
    "AlphaGrep": "alphagrep.com",
    "QuantCube": "quantcube.com",
    "Chronos Research": "chronosresearch.com",
    "Aspect Capital": "aspectcapital.com",
    "Winton": "winton.com",
    "Qube Research & Technologies": "qrtech.com",
    "AHL (Man Group AHL)": "man.com",
    "Citadel Quantitative Strategies": "citadel.com",
    "Two Sigma Securities": "twosigma.com",
    "Breen Capital": "breencapital.com",
    "Lansdowne Partners": "lansdownepartners.com",
    "Marshall Wace": "marshallwace.com",
    "Capula Investment Management": "capulainvestment.com",
    "Element Capital": "elementcapital.com",
    "BlueBay Asset Management": "bluebay.com",
    "Ruffer": "ruffer.co.uk",
    "Eisler Capital": "eislercapital.com",
    "Man Group GLG": "glgpartners.com",
    "Schonfeld Strategic Advisors": "schonfeld.com",
    "ExodusPoint Capital": "exoduspoint.com",
    "Caxton Associates": "caxton.com",
    "Anchorage Capital": "anchoragecap.com",
    "Odey Asset Management": "odey.com",
    "Light Street Capital": "lightstreetcapital.com",
    "D1 Capital Partners": "d1cap.com",
    "Egerton Capital": "egertoncapital.com",
    "Orbis Investment Management": "orbis.com",
    "Algebris Investments": "algebris.com",
    "Systematica Investments": "systematica.com"
}

# Additional aliases and legal-entity variants to improve matching coverage.
COMPANY_DOMAIN_ALIASES = {
    # Global banks and broker-dealers
    "J.P. Morgan": "jpmorgan.com",
    "JP Morgan": "jpmorgan.com",
    "JP Morgan Chase": "jpmorgan.com",
    "JPMorgan Chase": "jpmorgan.com",
    "JPMorgan Chase & Co": "jpmorgan.com",
    "JPMorgan Chase and Co": "jpmorgan.com",
    "JPMC": "jpmorgan.com",
    "JP Morgan Securities": "jpmorgan.com",
    "J.P. Morgan Securities": "jpmorgan.com",
    "JPMorgan Securities": "jpmorgan.com",
    "Bank of America Securities": "bofa.com",
    "Bank of America Merrill Lynch": "bofa.com",
    "BofA": "bofa.com",
    "BofA Securities": "bofa.com",
    "BAML": "bofa.com",
    "Merrill Lynch": "bofa.com",
    "Merrill": "bofa.com",
    "Merrill Lynch Wealth Management": "bofa.com",
    "Citi": "citi.com",
    "Citibank": "citi.com",
    "CitiGroup": "citi.com",
    "Citi Bank": "citi.com",
    "Citi Markets": "citi.com",
    "Citi Global Markets": "citi.com",
    "Citi Private Bank": "citi.com",
    "Morgan Stanley Wealth Management": "morganstanley.com",
    "Morgan Stanley Investment Management": "morganstanley.com",
    "MSIM": "morganstanley.com",
    "Morgan Stanley Smith Barney": "morganstanley.com",
    "MSSB": "morganstanley.com",
    "UBS AG": "ubs.com",
    "UBS Investment Bank": "ubs.com",
    "UBS Wealth Management": "ubs.com",
    "UBS Asset Management": "ubs.com",
    "Deutsche Bank AG": "db.com",
    "Deutsche Bank Securities": "db.com",
    "DB Securities": "db.com",
    "Barclays Capital": "barclays.com",
    "Barclays Investment Bank": "barclays.com",
    "Barclays CIB": "barclays.com",
    "BNPP": "bnpparibas.com",
    "BNP": "bnpparibas.com",
    "BNP Paribas CIB": "bnpparibas.com",
    "HSBC GBM": "hsbc.com",
    "HSBC Global Banking and Markets": "hsbc.com",
    "RBC Capital Markets": "rbc.com",
    "RBC CM": "rbc.com",
    "Royal Bank of Canada": "rbc.com",
    "BMO": "bmo.com",
    "BMO Financial Group": "bmo.com",
    "BMO Capital": "bmo.com",
    "TD": "tdsecurities.com",
    "TD Bank": "tdsecurities.com",
    "Toronto-Dominion Bank": "tdsecurities.com",
    "TD Cowen": "tdsecurities.com",
    "Wells Fargo Securities": "wellsfargo.com",
    "SocGen": "socgen.com",
    "Societe Generale": "socgen.com",
    "Societe Generale CIB": "socgen.com",
    "Nomura Securities": "nomura.com",
    "Mizuho Securities": "mizuho.com",
    "SMBC Nikko": "smbcgroup.com",
    "SMBC Nikko Securities": "smbcgroup.com",
    "MUFG Bank": "mufg.jp",
    "MUFG Securities": "mufg.jp",
    "NatWest Markets": "natwest.com",
    "Macquarie Capital": "macquarie.com",
    "Standard Chartered Bank": "sc.com",
    "ING Financial Markets": "ing.com",
    "ANZ Banking Group": "anz.com",
    "Santander": "santander.com",
    "Banco Santander": "santander.com",
    "Santander CIB": "santander.com",
    "Credit Agricole": "credit-agricole.com",
    "Credit Agricole CIB": "ca-cib.com",
    "BBVA": "bbva.com",
    "BBVA CIB": "bbva.com",
    "Rabobank": "rabobank.com",

    # Advisory / investment banking boutiques
    "Perella Weinberg Partners": "pwpartners.com",
    "PWP": "pwpartners.com",
    "Moelis & Company": "moelis.com",
    "Moelis and Company": "moelis.com",
    "Evercore ISI": "evercore.com",
    "PJT": "pjtpartners.com",
    "PJT Partners LP": "pjtpartners.com",
    "Centerview": "centerviewpartners.com",
    "Greenhill & Co": "greenhill.com",
    "Houlihan Lokey Capital": "hl.com",
    "Jefferies Financial Group": "jefferies.com",
    "Raymond James Financial": "raymondjames.com",
    "William Blair & Company": "williamblair.com",
    "Canaccord Genuity Group": "canaccordgenuity.com",
    "KeyBanc Capital Markets": "key.com",
    "Rothschild": "rothschildandco.com",
    "Rothschild and Co": "rothschildandco.com",
    "Guggenheim Partners": "guggenheimpartners.com",
    "Qatalyst Partners": "qatalyst.com",
    "FT Partners": "ftpartners.com",
    "Financial Technology Partners": "ftpartners.com",
    "Tudor Pickering Holt": "tudorpickeringholt.com",
    "TPH&Co": "tudorpickeringholt.com",

    # Asset management / institutional investors
    "Fidelity Investments": "fidelity.com",
    "FMR": "fidelity.com",
    "FMR LLC": "fidelity.com",
    "State Street Global Advisors": "ssga.com",
    "SSGA": "ssga.com",
    "Goldman Sachs Asset Management": "gs.com",
    "GSAM": "gs.com",
    "J.P. Morgan Asset Management": "jpmorgan.com",
    "JP Morgan Asset Management": "jpmorgan.com",
    "JPMorgan Asset Management": "jpmorgan.com",
    "JPMAM": "jpmorgan.com",
    "BlackRock Financial Management": "blackrock.com",
    "BlackRock Solutions": "blackrock.com",
    "AllianceBernstein LP": "alliancebernstein.com",
    "AB Bernstein": "alliancebernstein.com",
    "T Rowe Price": "troweprice.com",
    "T. Rowe Price Associates": "troweprice.com",
    "Neuberger Berman Group": "nb.com",
    "Lord Abbett & Co": "lordabbett.com",
    "Franklin Templeton Investments": "franklintempleton.com",
    "BNY Mellon Investment Management": "bnymellon.com",
    "Northern Trust Asset Management": "northerntrust.com",
    "Nuveen LLC": "nuveen.com",
    "Principal Global Investors": "principalglobal.com",
    "New York Life Investments": "nylim.com",
    "MetLife Investment Management": "metlifeinvestments.com",
    "Manulife Investment Management": "manulifeim.com",
    "Voya Investment Management": "voya.com",

    # Alternatives / private capital
    "Apollo Global Management": "apollo.com",
    "Blackstone Inc": "blackstone.com",
    "KKR & Co": "kkr.com",
    "Carlyle Group": "carlyle.com",
    "Ares Management": "aresmgmt.com",
    "Brookfield Asset Management": "brookfield.com",
    "Blue Owl Capital": "blueowl.com",
    "General Atlantic LLC": "generalatlantic.com",
    "Warburg Pincus LLC": "warburgpincus.com",
    "Silver Lake Partners": "silverlake.com",
    "Vista Equity Partners": "vistaequitypartners.com",
    "Advent International": "adventinternational.com",
    "Bain Capital LP": "baincapital.com",
    "Thoma Bravo": "thomabravo.com",
    "Hellman & Friedman": "hfgp.com",
    "TA Associates": "ta.com",
    "Francisco Partners": "franciscopartners.com",
    "Leonard Green & Partners": "leonardgreen.com",
    "Hg Capital": "hgcapital.com",
    "CVC Capital Partners": "cvc.com",
    "EQT Partners": "eqtgroup.com",

    # Hedge funds / quant
    "Citadel Securities LLC": "citadelsecurities.com",
    "D E Shaw": "deshaw.com",
    "DE Shaw": "deshaw.com",
    "Point72 Asset Management": "point72.com",
    "Millennium Management": "mlp.com",
    "Two Sigma Investments": "twosigma.com",
    "Bridgewater Associates": "bridgewater.com",
    "Balyasny Asset Management": "bamfunds.com",
    "Schonfeld Strategic Advisors": "schonfeld.com",
    "ExodusPoint Capital": "exoduspoint.com",
    "Marshall Wace": "marshallwace.com",
    "Elliott Management": "elliottmgmt.com",
    "Pershing Square": "pershingsquareholdings.com",
    "Third Point LLC": "thirdpoint.com",
    "Hudson River Trading": "hudsonrivertrading.com",
    "HRT": "hudsonrivertrading.com",
    "Susquehanna": "sig.com",

    # Ratings and market infrastructure
    "Moodys": "moodys.com",
    "Moody's": "moodys.com",
    "S&P Global": "spglobal.com",
    "SP Global": "spglobal.com",
    "S&P Global Ratings": "spglobal.com",
    "Fitch": "fitchratings.com",
    "Fitch Ratings": "fitchratings.com",
    "Bloomberg": "bloomberg.net",
    "Bloomberg LP": "bloomberg.net",

    # Additional major banks / broker-dealers
    "Jennison": "jennison.com",
    "PGIM": "pgim.com",
    "PGIM Fixed Income": "pgim.com",
    "PGIM Real Estate": "pgim.com",
    "Scotiabank": "scotiabank.com",
    "Scotia Capital": "scotiabank.com",
    "CIBC": "cibc.com",
    "CIBC Capital Markets": "cibc.com",
    "National Bank of Canada": "nbc.ca",
    "National Bank Financial": "nbc.ca",
    "Daiwa": "daiwa.co.jp",
    "Daiwa Capital Markets": "daiwacm.com",
    "Commerzbank": "commerzbank.com",
    "SEB": "sebgroup.com",
    "SEB CIB": "sebgroup.com",
    "Intesa Sanpaolo": "intesasanpaolo.com",
    "UniCredit": "unicreditgroup.eu",
    "Brown Brothers Harriman": "bbh.com",
    "BBH": "bbh.com",
    "Berenberg": "berenberg.com",
    "Mediobanca": "mediobanca.com",
    "Piper Jaffray": "pipersandler.com",
    "Piper": "pipersandler.com",
    "PJ Solomon": "pjsolomon.com",
    "Solomon Partners": "solomonpartners.com",
    "DC Advisory": "dcadvisory.com",
    "Alantra": "alantra.com",
    "Arma Partners": "armapartners.com",
    "Nomura Greentech": "nomuragreentech.com",

    # Additional major asset managers / institutional platforms
    "State Street Corporation": "statestreet.com",
    "State Street Global Markets": "statestreet.com",
    "Lazard Asset Management": "lazardassetmanagement.com",
    "M and G Investments": "mandg.com",
    "M&G Investments": "mandg.com",
    "Allspring": "allspringglobal.com",
    "Allspring Global Investments": "allspringglobal.com",
    "J O Hambro Capital Management": "johcm.com",
    "J O Hambro": "johcm.com",
    "Vanguard Group": "vanguard.com",
    "Schwab": "schwab.com",
    "Charles Schwab": "schwab.com",
    "Fidelity International": "fil.com",

    # Additional alternatives / private capital
    "GTCR": "gtcr.com",
    "HIG Capital": "hig.com",
    "H I G Capital": "hig.com",
    "Apax Partners": "apax.com",
    "Cinven": "cinven.com",
    "Berkshire Partners": "berkshirepartners.com",
    "CD&R": "cdr-inc.com",
    "Clayton Dubilier and Rice": "cdr-inc.com",
    "Brevan Howard": "brevanhoward.com",
    "Winton Group": "winton.com",

    # Additional market infrastructure / data providers
    "Morningstar": "morningstar.com",
    "MSCI": "msci.com",
    "LSEG": "lseg.com",
    "London Stock Exchange Group": "lseg.com",
    "FTSE Russell": "lseg.com",
    "Intercontinental Exchange": "ice.com",
    "ICE": "ice.com",
    "CME Group": "cmegroup.com",
    "Nasdaq": "nasdaq.com",
    "Cboe": "cboe.com",
}

COMPANY_DOMAINS.update(COMPANY_DOMAIN_ALIASES)

def get_company_domain(company: str) -> str | None:
    return COMPANY_DOMAINS.get(company)
